Feature/docs paths
amplication/amplication-site pull request #195
Opened 2022-06-30 15:05 UTC by shaharblanksela

Added new dynamic path_rule for the following redirects written on #194 .

2022-06-30 15:27 UTC, mshidlov commented
terraform plan production

2022-07-04 12:51 UTC, yuval-hazaz requested changes
@shaharblanksela @mshidlov please see my comments

2022-07-04 12:51 UTC, yuval-hazaz commented on terraform/main.tf
> +  }
please replace with a dynamic redirect

2022-07-04 12:51 UTC, yuval-hazaz commented on terraform/main.tf
> +# }
why did we remove all this?

2022-07-04 13:41 UTC, shaharblanksela commented on terraform/main.tf
> +# }
it just for testing i put it all back

2022-07-04 13:42 UTC, shaharblanksela commented on terraform/main.tf
> +}
you can look on my issue what I've tried to do. #196

2022-07-04 13:56 UTC, merged