Feature: Adding FAQs to Pricing Page
amplication/amplication-site pull request #437
Opened 2023-11-29 07:17 UTC by dericksozo

…he main amplication website, and adding some questions that we'll also add to the in-app pricing page.

Fixes: amplication/amplication#[issue-number]

## PR Details

## PR Checklist

- [ ] `npm run test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

2023-11-30 07:32 UTC, PazYanoverr approved these changes

2023-11-30 07:35 UTC, PazYanoverr commented
Waiting with the merge for the reverse trial and new packaging to be implemented

2023-12-14 14:47 UTC, PazYanoverr requested changes
Let's improve the visibility of the FAQ-
1. It's hard to distinguish between the questions and the answer, so let's try to improve it.
2. The text is in **bold** - no need for that

2023-12-14 14:47 UTC, PazYanoverr commented on components/Sections/Pricing/PricingFAQ/index.jsx
> +              question="We have our own best practices and standards - can we ask Amplication to generate the code in our own flavor?"
Let's talk here also about the private plugins

2023-12-15 04:00 UTC, dericksozo commented
Hi @PazYanoverr, the above two commits implements your feedback. Please let me know if there are any additional changes to be made.

2023-12-17 08:08 UTC, yuval-hazaz approved these changes

2023-12-17 08:08 UTC, merged