Update: Plugins page docs links
amplication/amplication-site pull request #445
Opened 2023-12-25 09:10 UTC by dericksozo

(update): Updating the links to the documentation for plugins on the /plugins page.

Fixes: amplication/amplication#[issue-number]

## PR Details

## PR Checklist

- [ ] `npm run test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

2023-12-26 07:49 UTC, yuval-hazaz requested changes

2023-12-26 07:49 UTC, yuval-hazaz commented on pages/plugins.js
> +              href="https://docs.amplication.com/contributing/"
let's use this URL instead 

https://github.com/amplication/amplication/issues/new?assignees=&labels=type%3A+feature+request&projects=&template=feature.yml

2023-12-26 08:33 UTC, dericksozo commented
Hey @yuval-hazaz, this latest commit implements your feedback.

2023-12-27 18:21 UTC, yuval-hazaz approved these changes

2023-12-28 07:40 UTC, merged